Traceback (most recent call last):
  File "C:\Users\Miguel\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Miguel\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Miguel\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\Miguel\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\Miguel\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Miguel\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Miguel\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Model Inputs
points = np.array(data["users"])

# Define and fit model (window with 90 width and l2 loss)
algo = rpt.Window(width=30, model="l2").fit(data["users"])

# Predict breakpoints - either manually or via penalization factor (this example)
breakpoints = algo.predict(pen=np.log(len(points)) * 2 * np.var(points)/2) # just an example, see docs for more information.

# Defining number of break points manually is also possible
# breakpoints = algo.predict(n_bkps=10) # or define number of break points manually

# Display results
rpt.show.display(points, breakpoints, figsize=(10, 6))
plt.title('Change Point Detection: Window-Based Search With Penalty Factor')
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mAttributeError[0m                            Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_27220\1868564388.py[0m in [0;36m?[1;34m()[0m
[0;32m      1[0m [1;31m# Model Inputs[0m[1;33m[0m[1;33m[0m[0m
[0;32m      2[0m [0mpoints[0m [1;33m=[0m [0mnp[0m[1;33m.[0m[0marray[0m[1;33m([0m[0mdata[0m[1;33m[[0m[1;34m"users"[0m[1;33m][0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      3[0m [1;33m[0m[0m
[0;32m      4[0m [1;31m# Define and fit model (window with 90 width and l2 loss)[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 5[1;33m [0malgo[0m [1;33m=[0m [0mrpt[0m[1;33m.[0m[0mWindow[0m[1;33m([0m[0mwidth[0m[1;33m=[0m[1;36m30[0m[1;33m,[0m [0mmodel[0m[1;33m=[0m[1;34m"l2"[0m[1;33m)[0m[1;33m.[0m[0mfit[0m[1;33m([0m[0mdata[0m[1;33m[[0m[1;34m"users"[0m[1;33m][0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      6[0m [1;33m[0m[0m
[0;32m      7[0m [1;31m# Predict breakpoints - either manually or via penalization factor (this example)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      8[0m [0mbreakpoints[0m [1;33m=[0m [0malgo[0m[1;33m.[0m[0mpredict[0m[1;33m([0m[0mpen[0m[1;33m=[0m[0mnp[0m[1;33m.[0m[0mlog[0m[1;33m([0m[0mlen[0m[1;33m([0m[0mpoints[0m[1;33m)[0m[1;33m)[0m [1;33m*[0m [1;36m2[0m [1;33m*[0m [0mnp[0m[1;33m.[0m[0mvar[0m[1;33m([0m[0mpoints[0m[1;33m)[0m[1;33m/[0m[1;36m2[0m[1;33m)[0m [1;31m# just an example, see docs for more information.[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\ruptures\detection\window.py[0m in [0;36m?[1;34m(self, signal)[0m
[0;32m    110[0m             [0mself[0m[1;33m[0m[1;33m[0m[0m
[0;32m    111[0m         """
[0;32m    112[0m         [1;31m# update some params[0m[1;33m[0m[1;33m[0m[0m
[0;32m    113[0m         [1;32mif[0m [0msignal[0m[1;33m.[0m[0mndim[0m [1;33m==[0m [1;36m1[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 114[1;33m             [0mself[0m[1;33m.[0m[0msignal[0m [1;33m=[0m [0msignal[0m[1;33m.[0m[0mreshape[0m[1;33m([0m[1;33m-[0m[1;36m1[0m[1;33m,[0m [1;36m1[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    115[0m         [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    116[0m             [0mself[0m[1;33m.[0m[0msignal[0m [1;33m=[0m [0msignal[0m[1;33m[0m[1;33m[0m[0m
[0;32m    117[0m         [0mself[0m[1;33m.[0m[0mn_samples[0m[1;33m,[0m [0m_[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0msignal[0m[1;33m.[0m[0mshape[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\generic.py[0m in [0;36m?[1;34m(self, name)[0m
[0;32m   6200[0m             [1;32mand[0m [0mname[0m [1;32mnot[0m [1;32min[0m [0mself[0m[1;33m.[0m[0m_accessors[0m[1;33m[0m[1;33m[0m[0m
[0;32m   6201[0m             [1;32mand[0m [0mself[0m[1;33m.[0m[0m_info_axis[0m[1;33m.[0m[0m_can_hold_identifiers_and_holds_name[0m[1;33m([0m[0mname[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m   6202[0m         ):
[0;32m   6203[0m             [1;32mreturn[0m [0mself[0m[1;33m[[0m[0mname[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 6204[1;33m         [1;32mreturn[0m [0mobject[0m[1;33m.[0m[0m__getattribute__[0m[1;33m([0m[0mself[0m[1;33m,[0m [0mname[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;31mAttributeError[0m: 'Series' object has no attribute 'reshape'

